server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql-smartcollab-prod.mysql.database.azure.com:3306/smartcollabdb?sslMode=REQUIRED&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${SPRING_DATASOURCE_USERNAME}   # schadmin
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

file:
  storage:
    mode: azure       # ← prod에서만 azure
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    container-name: uploads

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration-hours: 3
