spring:
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc.time_zone: Asia/Seoul
        dialect: org.hibernate.dialect.MySQLDialect # MySQL 8 Dialect
        format_sql: true

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 800MB   # 업로드 파일 최대 크기 (필요에 따라 조절)
      max-request-size: 800MB

  cloud:
    azure:
      storage:
        blob:

          container-name: smartcollab-files

jwt:

  secret-key: ${JWT_SECRET_KEY}

deepl:
  api:
    key: ${DEEPL_API_KEY:}
    endpoint: ${DEEPL_API_ENDPOINT:https://api-free.deepl.com}